// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const IconLaBars: typeof import('~icons/la/bars.jsx')['default']
  const IconLaInfo: typeof import('~icons/la/info.jsx')['default']
}
export {}
