// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const IconLaBars: typeof import('~icons/la/bars.jsx')['default']
  const IconLaPenSquare: typeof import('~icons/la/pen-square.jsx')['default']
}
export {}
