// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const IconLaBars: typeof import('~icons/la/bars.jsx')['default']
  const IconLaBuilding: typeof import('~icons/la/building.jsx')['default']
  const IconLaCalendar: typeof import('~icons/la/calendar.jsx')['default']
  const IconLaExclamationCircle: typeof import('~icons/la/exclamation-circle.jsx')['default']
  const IconLaMoneyBill: typeof import('~icons/la/money-bill.jsx')['default']
  const IconLaPlusCircle: typeof import('~icons/la/plus-circle.jsx')['default']
  const IconLaUserGraduate: typeof import('~icons/la/user-graduate.jsx')['default']
}
export {}
